DROP DATABASE API;

CREATE DATABASE API;

USE API;

CREATE TABLE CURSO (
	CURSO_ID INT AUTO_INCREMENT,
    CURSO_NOME VARCHAR(50) NOT NULL,
    CURSO_SIGLA VARCHAR(5) UNIQUE NOT NULL,
    PRIMARY KEY(CURSO_ID)
);

CREATE TABLE GRUPO (
    GRUPO_ID INT AUTO_INCREMENT,
    GRUPO_NOME VARCHAR(20) NOT NULL UNIQUE,
    REPOS_LINK VARCHAR(255) NOT NULL,
    CURSO_SIGLA VARCHAR(5) NOT NULL,
    SEMESTRE VARCHAR(10) NOT NULL,
    PRIMARY KEY (GRUPO_ID),
    FOREIGN KEY (CURSO_SIGLA) REFERENCES CURSO(CURSO_SIGLA)
);

CREATE TABLE ALUNO (
    ALUNO_RA BIGINT NOT NULL,                 
    ALUNO_EMAIL VARCHAR(30) NOT NULL UNIQUE,   
    ALUNO_NOME VARCHAR(100) NOT NULL,
    ALUNO_SENHA VARCHAR(30),
    FOTO LONGBLOB,
    GRUPO_ID INT,
    CURSO_SIGLA VARCHAR(5) NOT NULL,
    SEMESTRE VARCHAR(10) NOT NULL,
    PRIMARY KEY (ALUNO_RA),
    FOREIGN KEY (CURSO_SIGLA) REFERENCES CURSO(CURSO_SIGLA),
    FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO(GRUPO_ID)
);

CREATE TABLE PROFESSOR (
    PROF_ID INT AUTO_INCREMENT,
    PROF_NOME VARCHAR(100) NOT NULL,
    PROF_EMAIL VARCHAR(30) NOT NULL UNIQUE,  
    PROF_SENHA VARCHAR(30) NOT NULL,
    FOTO LONGBLOB,
    PRIMARY KEY (PROF_ID)
);

CREATE TABLE MATERIA (
    MATERIA_ID INT AUTO_INCREMENT,
    MATERIA_NOME VARCHAR(30) NOT NULL,
    MATERIA_SEMESTRE INT NOT NULL,
    PRIMARY KEY (MATERIA_ID)
);

CREATE TABLE CRITERIOS (
    CRITERIO_ID INT AUTO_INCREMENT,            
    CRITERIO_NOME VARCHAR(50) NOT NULL,
    CRITERIO_DESCRICAO VARCHAR(600),
    CRITERIO_ATIVO BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (CRITERIO_ID)
);

CREATE TABLE AVALIACAO (
    AVALIACAO_ID INT AUTO_INCREMENT,
    AVALIADO_ALUNO_RA BIGINT NOT NULL,
    AVALIADOR_ALUNO_RA BIGINT NOT NULL,
    CRITERIO_ID INT NOT NULL,
    NOTA DECIMAL(3,1) NOT NULL,
    AVALIACAO_DATA DATETIME NOT NULL,
    PRIMARY KEY (AVALIACAO_ID),
    FOREIGN KEY (AVALIADO_ALUNO_RA) REFERENCES ALUNO(ALUNO_RA),
    FOREIGN KEY (AVALIADOR_ALUNO_RA) REFERENCES ALUNO(ALUNO_RA),
    FOREIGN KEY (CRITERIO_ID) REFERENCES CRITERIOS(CRITERIO_ID)
);

CREATE TABLE SPRINT (
    SPRINT_ID INT AUTO_INCREMENT,
    SPRINT_NUM INT NOT NULL,
    SPRINT_SEMESTRE INT NOT NULL,
    SPRINT_DATA_INICIO DATE NOT NULL,
    SPRINT_DATA_FIM DATE NOT NULL,
    CONSTRAINT CK_SPRINT CHECK (SPRINT_NUM IN (1,2,3,4)),
    PRIMARY KEY (SPRINT_ID)
);

CREATE TABLE CALENDARIO (
    CALENDARIO_ID INT AUTO_INCREMENT,
    SEMESTRE VARCHAR(10) NOT NULL,
    SPRINT_ID INT,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    PRIMARY KEY (CALENDARIO_ID),
    FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT(SPRINT_ID)
);

-- Inserindo dados na tabela CURSO
INSERT INTO CURSO (CURSO_NOME, CURSO_SIGLA) VALUES
('Ciência da Computação', 'CC'),
('Engenharia de Software', 'ES'),
('Sistemas de Informação', 'SI');

-- Inserindo dados na tabela GRUPO
INSERT INTO GRUPO (GRUPO_NOME, REPOS_LINK, CURSO_SIGLA, SEMESTRE) VALUES
('Grupo A', 'https://github.com/GrupoA', 'CC', '2024-1'),
('Grupo B', 'https://github.com/GrupoB', 'ES', '2024-1'),
('Grupo C', 'https://github.com/GrupoC', 'SI', '2024-2');

-- Inserindo dados na tabela ALUNO
INSERT INTO ALUNO (ALUNO_RA, ALUNO_EMAIL, ALUNO_NOME, ALUNO_SENHA, FOTO, GRUPO_ID, CURSO_SIGLA, SEMESTRE) VALUES
(12345678901, 'aluno1@example.com', 'João Silva', 'senha123', NULL, 1, 'CC', '2024-1'),
(12345678902, 'aluno2@example.com', 'Maria Oliveira', 'senha456', NULL, 2, 'ES', '2024-1'),
(12345678903, 'aluno3@example.com', 'Carlos Pereira', 'senha789', NULL, 3, 'SI', '2024-2');

-- Inserindo dados na tabela PROFESSOR
INSERT INTO PROFESSOR (PROF_NOME, PROF_EMAIL, PROF_SENHA, FOTO) VALUES
('Prof. Ana Costa', 'ana.costa@example.com', 'senhaAna', NULL),
('Prof. Bruno Almeida', 'bruno.almeida@example.com', 'senhaBruno', NULL),
('Prof. Carla Lima', 'carla.lima@example.com', 'senhaCarla', NULL);

-- Inserindo dados na tabela MATERIA
INSERT INTO MATERIA (MATERIA_NOME, MATERIA_SEMESTRE) VALUES
('Programação I', 1),
('Estruturas de Dados', 2),
('Banco de Dados', 2);

-- Inserindo dados na tabela CRITERIOS
INSERT INTO CRITERIOS (CRITERIO_NOME, CRITERIO_DESCRICAO, CRITERIO_ATIVO) VALUES
('Entregas', 'Avaliação de todas as entregas feitas pelo aluno.', TRUE),
('Participação', 'Avaliação da participação em sala de aula.', TRUE);

-- Inserindo dados na tabela AVALIACAO
INSERT INTO AVALIACAO (AVALIADO_ALUNO_RA, AVALIADOR_ALUNO_RA, CRITERIO_ID, NOTA, AVALIACAO_DATA) VALUES
(12345678901, 12345678902, 1, 8.5, '2024-11-01 10:00:00'),
(12345678902, 12345678903, 2, 7.0, '2024-11-01 11:00:00'),
(12345678903, 12345678901, 1, 9.0, '2024-11-01 12:00:00');

-- Inserindo dados na tabela SPRINT
INSERT INTO SPRINT (SPRINT_NUM, SPRINT_SEMESTRE, SPRINT_DATA_INICIO, SPRINT_DATA_FIM) VALUES
(1, 1, '2024-11-01', '2024-11-14'),
(2, 1, '2024-11-15', '2024-11-30'),
(3, 2, '2024-12-01', '2024-12-14');

-- Inserindo dados na tabela CALENDARIO
INSERT INTO CALENDARIO (SEMESTRE, SPRINT_ID, DATA_INICIO, DATA_FIM) VALUES
('2024-1', 1, '2024-11-01', '2024-11-14'),
('2024-1', 2, '2024-11-15', '2024-11-30'),
('2024-2', 3, '2024-12-01', '2024-12-14');


USE API;
SELECT * FROM ALUNO;
SELECT * FROM PROFESSOR;
SELECT * FROM GRUPO;
SELECT * FROM SEMESTRE;